site_name: Thirdweb Python SDK

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.indexes

    

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

extra_css:
  - css/autodoc.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/thirdweb_
    - icon: fontawesome/brands/discord
      link: https://discord.gg/thirdweb