site_name: Thirdweb Python SDK

theme:
  logo: images/logo.png
  favicon: images/logo.png
  name: material
  features:
    - navigation.tracking
    - navigation.indexes
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


    

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

extra_css:
  - css/autodoc.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/thirdweb_
    - icon: fontawesome/brands/discord
      link: https://discord.gg/thirdweb