name: Run Unit Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  tests:
    name: "Run unit tests against Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: "3.6,3.8"
      PKEY: ${{ secrets.PKEY }}

    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.6", "3.7", "3.8", "pypy3"]

    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync -d

      - name: "Run tests targets for ${{ matrix.python-version }}"
        run: pipenv run tests

      - name: "Test bundle package with setup.py ${{ matrix.python-version }}"
        run: "python3 setup.py sdist"
